### ISSUE TITLE
StructuredNode.refresh() causes IndexError when a node doesn't exist 

### ISSUE THREAD

**Issue by yarmash** [neo4j-contrib/neomodel#294]
Here's a complete reproducer:

```
from neomodel import StringProperty, StructuredNode, UniqueIdProperty, config

config.DATABASE_URL = 'bolt://neo4j:passw0rd@localhost:7687'


class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty()


person = Person(name="John Doe").save()

# in some other function..
Person.nodes.get(name="John Doe").delete()

person.refresh()

```

Output:

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    person.refresh()
  File "{...}/neomodel/core.py", line 280, in refresh
    " RETURN n")[0][0][0])
IndexError: list index out of range
```

**Comment by aanastasiou** [comment]
@yarmash Just tried this and received `Can't fresh non-existent node`, can you please confirm that this persists in `3.3.1`?
