### ISSUE TITLE
AttributeError: 'Relationship' object has no attribute 'start_node' [3.3.1]

### ISSUE THREAD

**Issue by MrGreenTea** [neo4j-contrib/neomodel#414]
I can't seem to get StructuredRel wo work. The Relationship is actually created in neo4j, but I get the following Attribute Error. I am using python3.7 with neomodel 3.3.1

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "~/.pyenv/versions/test_env/lib/python3.7/site-packages/neomodel/relationship_manager.py", line 24, in checker
    return fn(self, *args, **kwargs)
  File "~/.pyenv/versions/test_env/lib/python3.7/site-packages/neomodel/relationship_manager.py", line 103, in connect
    rel_instance = self._set_start_end_cls(rel_model.inflate(rel_), node)
  File "~/.pyenv/versions/test_env/lib/python3.7/site-packages/neomodel/relationship.py", line 93, in inflate
    srel._start_node_id = rel.start_node.id
AttributeError: 'Relationship' object has no attribute 'start_node'
```

I can reproduce this Error with the following code

```python
from neomodel import StructuredNode, StructuredRel, properties, Relationship

class TestRel(StructuredRel):
    test_property = properties.StringProperty()
    
class TestNode(StructuredNode):
    test_rel = Relationship("TestNode", "TEST", model=TestRel)
    
t = TestNode().save()
t2 = TestNode().save()

t.test_rel.connect(t2, {"test_property": "test_value"})
```

**Comment by MrGreenTea** [comment]
changing the lines in StructuredRel.inflate to
```python
srel._start_node_id = rel.start
srel._end_node_id = rel.end
```

seems to fix the problem.

**Comment by MrGreenTea** [comment]
Okay this was a weird one. Somehow pip installed version 1.5.3 of neo4j driver. After updating it, everything works correctly now.

**Comment by MrGreenTea** [comment]
Maybe `setup.py` should be updated to require a more up-to-date version of the `neo4j-driver` (which is deprecated and should be changed to just `neo4j` package) ? The version of neomodel is als still 3.3.0 in `setup.py`.
