### ISSUE TITLE
ImportError: cannot import name 'Node', python version 3.6.2 && neo4j version 3.5

### ISSUE THREAD

**Issue by flylzj** [neo4j-contrib/neomodel#423]
When i run [this example](https://neomodel.readthedocs.io/en/latest/getting_started.html#definition) i got an import error.

```
Traceback (most recent call last):
  File "F:/mycode/python/graphdatabase/main.py", line 2, in <module>
    from neomodel import (config, StructuredNode, StringProperty, IntegerProperty,
  File "F:\mycode\python\graphdatabase\venv\lib\site-packages\neomodel\__init__.py", line 3, in <module>
    from .core import *
  File "F:\mycode\python\graphdatabase\venv\lib\site-packages\neomodel\core.py", line 9, in <module>
    from neomodel.util import Database, classproperty, _UnsavedNode, _get_node_properties
  File "F:\mycode\python\graphdatabase\venv\lib\site-packages\neomodel\util.py", line 8, in <module>
    from neo4j.v1 import GraphDatabase, basic_auth, CypherError, SessionError, Node
ImportError: cannot import name 'Node'
```

My code:

```
# coding: utf-8
from neomodel import (config, StructuredNode, StringProperty, IntegerProperty,
    UniqueIdProperty, RelationshipTo, RelationshipFrom)

config.DATABASE_URL = 'bolt://neo4j:mypassword@localhost:7687'

class Country(StructuredNode):
    code = StringProperty(unique_index=True, required=True)

    # traverse incoming IS_FROM relation, inflate to Person objects
    inhabitant = RelationshipFrom('Person', 'IS_FROM')


class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)

    # traverse outgoing IS_FROM relations, inflate to Country objects
    country = RelationshipTo(Country, 'IS_FROM')
```

**Comment by aanastasiou** [comment]
Please see [here](https://github.com/neo4j-contrib/neomodel/pull/415).

**Comment by flylzj** [comment]
i works，thanks

**Comment by aanastasiou** [comment]
@flylzj No worries, will make sure this is fixed, hopefully by the next release.
