### ISSUE TITLE
Replace {var} style variables with $var

### ISSUE THREAD

**Issue by KevinvOosterhout** [neo4j-contrib/neomodel#487]
Since Neo4j 3.0 {var} style variables have been deprecated. This has been replaced by $vars. All neo4j 3.x versions prefer this style and neo4j 4.x versions require this style of variables. It's however not compatible with neo4j < 3.0.  

=== EDIT ===
This is required for 4.0 support

**Comment by aanastasiou** [comment]
Thank you, will take a look at this soon

**Comment by aanastasiou** [comment]
Had a first scan on tackling this and from this, the changes seem to be straightforward. 

The bulk of those changes are in modules `match.py`, `match_q.py`, `relationship.py` and `relationship_manager.py` and a couple in `util.py`.

**Comment by aanastasiou** [comment]
@KevinvOosterhout Can you please post the complete trace that motivated this report?

**Comment by JVemmer** [comment]
@aanastasiou I am not the original poster, but I created a test database to get a full traceback. (currently facing this issue as well)

> Test.nodes.get(uid='1234')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/match.py", line 551, in get
    result = self._get(limit=2, lazy=lazy, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/match.py", line 542, in _get
    return self.query_cls(self).build_ast()._execute(lazy)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/match.py", line 447, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 33, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 229, in cypher_query
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 212, in cypher_query
    response = session.run(query, params)
  File "/home/username/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 45 (offset: 44))
" MATCH ((test:Test)) WHERE test.uid = {test_uid_1} RETURN test LIMIT 2"

**Comment by JVemmer** [comment]
For anyone who needs to get their environments running asap, one workaround is to set `cypher.default_language_version=3.5` in the server config file, until this gets sorted.
This is a very temporary workaround, as Neo4j removes support for older Cypher versions regularly.

Reference: https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#cypher-compatibility

**Comment by aanastasiou** [comment]
@JVemmer Thank you very much. I am working through it. Can I please ask you to try [this one](https://github.com/aanastasiou/neomodel)? I am working through the constraint errors at the moment.

**Comment by JVemmer** [comment]
@aanastasiou I tested the changes.
Able to use without issues:
- .get()
- .save()
- .all()

Able to use with some caveats:
- .filter() works, but the 'in' option currently does not work, since the re.sub call you added changes the passed list to a string, which does not work (it expects a list). Traceback at the end of this comment.

Not able to use:
- Relationship iteration; trying to get any related nodes via relationships just returns an empty list. (yes, I double-checked via Neo4j Browser that the relationships were actually there)
- Explicit traversal; similar to above, it just returns an empty list.

Is there anything else you would like me to test?

The traceback for the filter issue, if needed:

> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/match.py", line 475, in __iter__
    return (i for i in self.query_cls(self).build_ast()._execute())
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/match.py", line 447, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 231, in cypher_query
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 215, in cypher_query
    results, meta = [list(r.values()) for r in response], response.keys()
  File "/home/username/.local/lib/python3.8/site-packages/neomodel/util.py", line 215, in <listcomp>
    results, meta = [list(r.values()) for r in response], response.keys()
  File "/home/username/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 935, in records
    self._session.fetch()
  File "/home/username/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 516, in fetch
    detail_count, _ = self._connection.fetch()
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/username/.local/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherTypeError: Expected list, got String("('Hello', 'World', 'Testing')")

**Comment by aanastasiou** [comment]
@JVemmer Thank you, will be in touch later today. Can you please run the tests and let me know (in summary) the results?

**Comment by aanastasiou** [comment]
@juanmhidalgo Is it possible for you to handle the necessary substitutions for this, in `neomodel/match.py` and `neomodel/match_q.py`?

**Comment by JVemmer** [comment]
Hi @aanastasiou,
Any status on this? I have currently resorted to rewriting everything in pure Cypher, using neomodel.db.cypher_query, but it is rather cumbersome compared to using the models.
Also, if there is anything I can do to help, let me know.

**Comment by aanastasiou** [comment]
Hi @JVemmer , thank you.

I have not worked on the query side much and this is why I asked @juanmhidalgo to have a look. Then I started looking more closely on how are the `neomodel` commands get translated to cypher queries to pinpoint which pairs of `{}` need change. 

The whole "magic" is happening in [`match.py`](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/match.py). As the queries get built up using `neomodel` functions, what is created is an intermediate form of the query, very similar to how an abstract syntax tree (AST) gets build up from the parsing of an expression. In the end, this AST is traversed and the actual statement gets built up. This is taking place within all `build_` prefixed functions within the same file (`match.py`).

And this is where I am at the moment.

If you would like to give us a hand with pinpointing the right `{}` to translate to `$`, that would be great. You can spot them almost automatically because they look like `{{ }}` but you need to confirm where they are.

All the best

**Comment by JVemmer** [comment]
Hi @aanastasiou, I created #490 for this.

**Comment by davidmoseler** [comment]
@TrietDHA I've made a minor fix to @aanastasiou pull request which allows you to run neomodel with neo4j 4.0. You just need to run

`python -m pip install git+https://github.com/davidmoseler/neomodel.git`

**Comment by gitkp11** [comment]
Still the same issue persists in latest version till today's date. I have created issue for it in neomodel. Please can someone check it.
[here's the issue](https://github.com/neo4j-contrib/django-neomodel/issues/43#issue-762242245)

**Comment by AntonLydike** [comment]
I believe this was fixed with the transition to neo4j 4. Feel free to re-open if I'm wrong!
