### ISSUE TITLE
TypeError: 'ZeroOrMore' object is not callable

### ISSUE THREAD

**Issue by tdoan2010** [neo4j-contrib/neomodel#516]
Hi, I got a strange behavior of `neomodel 3.3.2`. For example, my model looks like this:
```
class AuthorCreate(StructuredRel):
    role = StringProperty()


class Author(StructuredNode):
    name = StringProperty(required=True)
    create = RelationshipTo(Collection, 'CREATE', model=AuthorCreate)
```
Then, I use it like this:
```
author_node = Author(name='Test author node').save()
```
And I got exception:
```
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 33, in main
    author_node = Author(name='Test author node').save()
  File "/lib/python3.7/site-packages/neomodel/hooks.py", line 14, in hooked
    val = fn(self)
  File "/lib/python3.7/site-packages/neomodel/core.py", line 561, in save
    self.id = self.create(self.__properties__)[0].id
TypeError: 'ZeroOrMore' object is not callable

Process finished with exit code 1
```
If I comment out the line where I define the relationship for `Author`, it works fine again. It only happens when my model contains a relationship with `model`.

So, did I use it wrong? Or is it a bug?

**Comment by tdoan2010** [comment]
I solved the problem. The reason is the variable name of the relationship should not be called `create`. Just name it something else.
