### ISSUE TITLE
Issue with connecting to neo4j  from Apple Silicon

### ISSUE THREAD

**Issue by moredhel** [neo4j-contrib/neomodel#554]
I'm trying to run neomodel  from an apple silicon machine & am having some issues connecting to Neo4j.

I've tried connecting to the following versions:
- 4.1.8
- 4.2.4

It seems to be an issue with SSL connection.

```
Traceback (most recent call last):
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "models.py", line 37, in <module>
    print(User.nodes.all())
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neomodel/match.py", line 472, in all
    return self.query_cls(self).build_ast()._execute(lazy)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neomodel/match.py", line 447, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neomodel/util.py", line 32, in wrapper
    _db.set_connection(config.DATABASE_URL)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neomodel/util.py", line 93, in set_connection
    self.driver = GraphDatabase.driver(u.scheme + '://' + hostname,
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neo4j/__init__.py", line 108, in driver
    return Driver(uri, **config)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neo4j/__init__.py", line 147, in __new__
    return subclass(uri, **config)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neo4j/__init__.py", line 221, in __new__
    pool.release(pool.acquire())
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neo4j/__init__.py", line 218, in connector
    return connect(address, **dict(config, **kwargs))
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/Users/user/src/moredhel/config-mgmt/serv/venv/lib/python3.8/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1125)'
```

Let me know if i can provide more information.

I had a look through the following error: https://github.com/neo4j-contrib/neomodel/issues/378

**Comment by moredhel** [comment]
Closing as I believe this may be an issue with early Apple Silicon.
