### ISSUE TITLE
Using `connect` throws CypherSyntaxError -> Update `CREATE UNIQUE` to use `MERGE` instead

### ISSUE THREAD

**Issue by sadsongco** [neo4j-contrib/neomodel#569]
I am completely new to neo4j. My project is to build a Django REST API, and I wish to use neo4j, using django_neomodel.

I followed this tutorial:
`https://medium.com/swlh/create-rest-api-with-django-and-neo4j-database-using-django-nemodel-1290da717df9` [referred to as tutorial 1]
and when I hit problems, I worked through this tutorial as a check:
`https://neomodel.readthedocs.io/en/latest/getting_started.html` [referred to as tutorial 2]

In tutorial 1 section 4, I test the database by running some commands in Django shell. Everything  works as expected and the created nodes can be observed in Neo4j Browser. When I run the line:
`sihem.city.connect(algiers)`
It generates this error:
```
neobolt.exceptions.CypherSyntaxError: Invalid input 'UNIQUE': expected "shortestPath", "allShortestPaths" or "(" (line 1, column 67 (offset: 66))
"MATCH (them), (us) WHERE id(them)={them} and id(us)={self} CREATE UNIQUE(us)-[r:`FRIEND`]-(them)"
```

When working through tutorial 2 in a fresh virtual environment, in the **Relationships** section, when calling
`jim.country.connect(germany)`
I get the same error. Full error below:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/relationship_manager.py", line 24, in checker
    return fn(self, *args, **kwargs)
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/relationship_manager.py", line 99, in connect
    self.source.cypher(q, params)
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/core.py", line 388, in cypher
    return db.cypher_query(query, params)
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/util.py", line 33, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/util.py", line 229, in cypher_query
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neomodel/util.py", line 212, in cypher_query
    response = session.run(query, params)
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neo4j/__init__.py", line 492, in run
    self._connection.fetch()
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/nigelpowell/Documents/Programming/CM3035Final/neomodel_env/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input 'UNIQUE': expected "shortestPath", "allShortestPaths" or "(" (line 1, column 67 (offset: 66))
"MATCH (them), (us) WHERE id(them)={them} and id(us)={self} CREATE UNIQUE(us)-[r:`FRIEND`]-(them)"
```

The virtual environment is using these libraries / versions:

```
asgiref==3.4.1
Django==3.2.6
django-neomodel==0.0.4
neo4j-driver==1.7.2
neobolt==1.7.17
neomodel==3.3.2
neotime==1.7.4
pytz==2021.1
six==1.16.0
sqlparse==0.4.1
```

I'm on an Apple M1 MacbookPro running MacOS 11.4
Where is my mistake?

**Comment by whatSocks** [comment]
@sadsongco can you try to upgrade to neomodel version 4.0.5?

**Comment by sadsongco** [comment]
@whatSocks thank you that was it.
In case anyone else has the same problem, when running `pip install django_neomodel`, `Shapely` was failing on installation because I didn't have **geos** installed. Pip then rolled the **neomodel** version back to 3.3.2.
Solution on mac: `brew install geos` then reinstalled Django and django_neomodel, and it now works fine.
