### ISSUE TITLE
ValueError: Can't install traversal 'source' exists on NodeSet

### ISSUE THREAD

**Issue by zzzqiii** [neo4j-contrib/neomodel#606]
I used django neomodel to connect the Neo4j database which stored the relationships between genes.
This is the scheme visualization.
![image](https://user-images.githubusercontent.com/78252314/154806441-1ee464f2-7ed3-4469-b351-422430ff8317.png)

And this is my model for data.
```
class Genes(StructuredNode):
    id = StringProperty()
    name = StringProperty()
    source = RelationshipFrom('Genes', 'INTERACTION')
    target = RelationshipTo('Genes', 'INTERACTION')
```
When I run `len(GENE.nodes)` in python shell, it throws an error:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "G:\software\anaconda\envs\flybase\lib\site-packages\neomodel\util.py", line 344, in __get__
    return self.getter(type)
  File "G:\software\anaconda\envs\flybase\lib\site-packages\neomodel\core.py", line 266, in nodes
    return NodeSet(cls)
  File "G:\software\anaconda\envs\flybase\lib\site-packages\neomodel\match.py", line 581, in __init__
    install_traversals(self.source_class, self)
  File "G:\software\anaconda\envs\flybase\lib\site-packages\neomodel\match.py", line 172, in install_traversals
    raise ValueError("Can't install traversal '{0}' exists on NodeSet".format(key))
ValueError: Can't install traversal 'source' exists on NodeSet

Any hint would be helpful.

**Comment by zzzqiii** [comment]
solved it by change class attribute 'source'.
